version: '3.1'

volumes:
  local_pg_data: {}

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - local_pg_data:/var/lib/postgresql/auth-starter
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_starter

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: auth_starter_mailhog
    ports:
      - '8025:8025'
      - '1025:1025'